//
//  SFSymbolManager.swift
//  Seahorse
//
//  Created by caishilin on 2025/11/14.
//

import Foundation
import SwiftUI

class SFSymbolManager {
    static let shared = SFSymbolManager()

    private init() {}

    // MARK: - Available Icons (filtered by system availability)

    /// Returns all icons that are actually available on the current system
    var availableIcons: [String] {
        // Filter to only include symbols that exist on this macOS version
        return allIcons.filter { icon in
            #if os(macOS)
            NSImage(systemSymbolName: icon, accessibilityDescription: nil) != nil
            #else
            UIImage(systemName: icon) != nil
            #endif
        }
    }

    let allIcons: [String] = Array(Set([
        // MARK: - Arrows & Navigation (60+)
        "arrow.left", "arrow.right", "arrow.up", "arrow.down",
        "arrow.left.circle", "arrow.right.circle", "arrow.up.circle", "arrow.down.circle",
        "arrow.left.circle.fill", "arrow.right.circle.fill", "arrow.up.circle.fill", "arrow.down.circle.fill",
        "arrow.left.square", "arrow.right.square", "arrow.up.square", "arrow.down.square",
        "arrow.left.square.fill", "arrow.right.square.fill", "arrow.up.square.fill", "arrow.down.square.fill",
        "arrow.clockwise", "arrow.counterclockwise",
        "arrow.clockwise.circle", "arrow.counterclockwise.circle",
        "arrow.clockwise.circle.fill", "arrow.counterclockwise.circle.fill",
        "arrow.uturn.left", "arrow.uturn.right", "arrow.uturn.up", "arrow.uturn.down",
        "arrow.uturn.left.circle", "arrow.uturn.right.circle", "arrow.uturn.up.circle", "arrow.uturn.down.circle",
        "arrow.uturn.left.circle.fill", "arrow.uturn.right.circle.fill", "arrow.uturn.up.circle.fill", "arrow.uturn.down.circle.fill",
        "arrow.left.arrow.right", "arrow.up.arrow.down",
        "arrow.left.and.right", "arrow.up.and.down",
        "arrow.left.and.line.vertical.and.arrow.right",
        "arrow.up.and.line.horizontal.and.arrow.down",
        "arrow.triangle.left", "arrow.triangle.right", "arrow.triangle.up", "arrow.triangle.down",
        "arrow.triangle.left.fill", "arrow.triangle.right.fill", "arrow.triangle.up.fill", "arrow.triangle.down.fill",
        "arrow.triangle.2.circlepath", "arrow.triangle.capsulepath",
        "arrow.2.circlepath", "arrow.3.trianglepath",
        "arrow.merge", "arrow.swap",
        "arrow.turn.up.left", "arrow.turn.up.right",
        "arrow.turn.down.left", "arrow.turn.down.right",
        "chevron.left", "chevron.right", "chevron.up", "chevron.down",
        "chevron.left.circle", "chevron.right.circle", "chevron.up.circle", "chevron.down.circle",
        "chevron.left.circle.fill", "chevron.right.circle.fill", "chevron.up.circle.fill", "chevron.down.circle.fill",
        "chevron.compact.left", "chevron.compact.right", "chevron.compact.up", "chevron.compact.down",
        "chevron.left.2", "chevron.right.2", "chevron.up.2", "chevron.down.2",
        "chevron.left.slash.chevron.right",
        "forward", "backward", "play", "pause", "stop", "restart",
        "forward.circle", "backward.circle", "play.circle", "pause.circle", "stop.circle",
        "forward.circle.fill", "backward.circle.fill", "play.circle.fill", "pause.circle.fill", "stop.circle.fill",
        "forward.fill", "backward.fill", "play.fill", "pause.fill", "stop.fill",
        "play.rectangle", "play.rectangle.fill",
        "shuffle", "shuffle.circle", "shuffle.circle.fill",
        "repeat", "repeat.circle", "repeat.circle.fill",
        "repeat.1", "repeat.1.circle", "repeat.1.circle.fill",
        "goforward", "gobackward",
        "goforward.10", "gobackward.10",
        "goforward.15", "gobackward.15",
        "goforward.30", "gobackward.30",
        "goforward.45", "gobackward.45",
        "goforward.60", "gobackward.60",
        "goforward.75", "gobackward.75",
        "goforward.90", "gobackward.90",
        "goforward.plus", "gobackward.minus",

        // MARK: - Symbols & Shapes (80+)
        "circle", "circle.fill", "circle.dashed", "circle.dotted",
        "smallcircle.fill.circle", "smallcircle.fill.circle.fill",
        "circle.circle", "circle.circle.fill",
        "circle.square", "circle.square.fill",
        "circle.grid.2x2", "circle.grid.2x2.fill",
        "circle.grid.3x3", "circle.grid.3x3.fill",
        "circle.grid.cross", "circle.grid.cross.fill",
        "circle.hexagongrid", "circle.hexagongrid.fill",
        "circle.hexagonpath", "circle.hexagonpath.fill",
        "square", "square.fill", "square.dashed", "square.dotted",
        "square.circle", "square.circle.fill",
        "square.split.2x1", "square.split.2x1.fill",
        "square.split.1x2", "square.split.1x2.fill",
        "square.split.2x2", "square.split.2x2.fill",
        "square.split.bottomrightquarter", "square.split.bottomrightquarter.fill",
        "square.split.diagonal", "square.split.diagonal.fill",
        "square.grid.2x2", "square.grid.2x2.fill",
        "square.grid.3x3", "square.grid.3x3.fill",
        "square.grid.4x3.fill",
        "rectangle", "rectangle.fill", "rectangle.dashed", "rectangle.dotted",
        "rectangle.split.2x1", "rectangle.split.2x1.fill",
        "rectangle.split.1x2", "rectangle.split.1x2.fill",
        "rectangle.split.3x3", "rectangle.split.3x3.fill",
        "rectangle.split.inset.filled",
        "rectangle.portrait", "rectangle.portrait.fill",
        "rectangle.portrait.split.2x1", "rectangle.portrait.split.2x1.fill",
        "capsule", "capsule.fill",
        "capsule.portrait", "capsule.portrait.fill",
        "triangle", "triangle.fill",
        "diamond", "diamond.fill",
        "diamond.circle", "diamond.circle.fill",
        "octagon", "octagon.fill",
        "hexagon", "hexagon.fill",
        "pentagon", "pentagon.fill",
        "seal", "seal.fill",
        "shield", "shield.fill",
        "shield.lefthalf.fill", "shield.righthalf.fill",
        "shield.lefthalf.fill.badge.checkmark",
        "shield.lefthalf.fill.badge.xmark",
        "checkmark.shield", "xmark.shield",
        "star", "star.fill", "star.leadinghalf.fill", "star.trailinghalf.fill",
        "star.circle", "star.circle.fill",
        "star.square", "star.square.fill",
        "line.horizontal.3", "line.horizontal.3.circle", "line.horizontal.3.circle.fill",
        "line.horizontal.3.decrease", "line.horizontal.3.decrease.circle", "line.horizontal.3.decrease.circle.fill",
        "line.3.horizontal", "line.3.horizontal.circle", "line.3.horizontal.circle.fill",
        "line.3.horizontal.decrease", "line.3.horizontal.decrease.circle", "line.3.horizontal.decrease.circle.fill",
        "minus", "minus.circle", "minus.circle.fill", "minus.square", "minus.square.fill",
        "plus", "plus.circle", "plus.circle.fill", "plus.square", "plus.square.fill",
        "plusminus", "plusminus.circle", "plusminus.circle.fill",
        "minus.plus.batteryblock", "minus.plus.batteryblock.fill",
        "xmark", "xmark.circle", "xmark.circle.fill", "xmark.square", "xmark.square.fill",
        "xmark.diamond", "xmark.diamond.fill",
        "xmark.octagon", "xmark.octagon.fill",
        "checkmark", "checkmark.circle", "checkmark.circle.fill", "checkmark.square", "checkmark.square.fill",
        "checkmark.seal", "checkmark.seal.fill",
        "checkmark.rectangle", "checkmark.rectangle.fill",
        "checkmark.rectangle.portrait", "checkmark.rectangle.portrait.fill",
        "checkmark.shield", "checkmark.shield.fill",
        "questionmark", "questionmark.circle", "questionmark.circle.fill",
        "questionmark.square", "questionmark.square.fill",
        "questionmark.diamond", "questionmark.diamond.fill",
        "exclamationmark", "exclamationmark.circle", "exclamationmark.circle.fill",
        "exclamationmark.square", "exclamationmark.square.fill",
        "exclamationmark.octagon", "exclamationmark.octagon.fill",
        "exclamationmark.triangle", "exclamationmark.triangle.fill",
        "exclamationmark.shield", "exclamationmark.shield.fill",
        "questionmark.circle.dashed",

        // MARK: - Technology & Devices (100+)
        "laptopcomputer", "laptopcomputer.and.arrow.down",
        "desktopcomputer", "desktopcomputer.and.arrow.down",
        "macpro.gen1", "macpro.gen1.fill",
        "macpro.gen2", "macpro.gen2.fill",
        "macpro.gen3", "macpro.gen3.fill",
        "macstudio", "macstudio.fill",
        "macmini", "macmini.fill",
        "airport.express", "airport.express.fill",
        "airport.extreme", "airport.extreme.fill",
        "airport.extreme.tower", "airport.extreme.tower.fill",
        "xserve", "xserve.raid",
        "pc", "pc.fill",
        "keyboard", "keyboard.fill", "keyboard.chevron.compact.down", "keyboard.chevron.compact.down.fill",
        "keyboard.onehanded.left", "keyboard.onehanded.left.fill",
        "keyboard.onehanded.right", "keyboard.onehanded.right.fill",
        "printer", "printer.fill",
        "printer.dotmatrix", "printer.dotmatrix.fill",
        "scanner", "scanner.fill",
        "faxmachine", "faxmachine.fill",
        "tv", "tv.fill",
        "tv.inset.filled",
        "tv.circle", "tv.circle.fill",
        "tv.and.hifispeaker.fill",
        "tv.and.mediabox",
        "display", "display.fill",
        "display.trianglebadge.exclamationmark", "display.trianglebadge.exclamationmark.fill",
        "display.2", "display.2.fill",
        "server.rack",
        "hifi.receiver.and.speakers", "hifi.receiver.and.speakers.fill",
        "hifispeaker", "hifispeaker.fill",
        "hifispeaker.2", "hifispeaker.2.fill",
        "speaker", "speaker.fill",
        "speaker.circle", "speaker.circle.fill",
        "speaker.slash", "speaker.slash.fill",
        "speaker.slash.circle", "speaker.slash.circle.fill",
        "speaker.zzz", "speaker.zzz.fill",
        "speaker.wave.1", "speaker.wave.1.fill",
        "speaker.wave.2", "speaker.wave.2.fill",
        "speaker.wave.2.circle", "speaker.wave.2.circle.fill",
        "speaker.wave.3", "speaker.wave.3.fill",
        "speaker.wave.3.circle", "speaker.wave.3.circle.fill",
        "dot.radiowaves.left.and.right",
        "dot.radiowaves.right",
        "dot.radiowaves.forward",
        "antenna.radiowaves.left.and.right",
        "antenna.radiowaves.left.and.right.circle", "antenna.radiowaves.left.and.right.circle.fill",
        "antenna.radiowaves.left.and.right.slash",
        "iphone", "iphone.fill",
        "iphone.circle", "iphone.circle.fill",
        "iphone.radio", "iphone.radio.fill",
        "iphone.homebutton", "iphone.homebutton.fill",
        "iphone.homebutton.radio", "iphone.homebutton.radio.fill",
        "iphone.homebutton.slash", "iphone.homebutton.slash.fill",
        "iphone.smartbatterycase.gen2",
        "ipad", "ipad.fill",
        "ipad.homebutton", "ipad.homebutton.fill",
        "ipad.landscape", "ipad.landscape.fill",
        "ipad.homebutton.landscape", "ipad.homebutton.landscape.fill",
        "ipod", "ipod.fill",
        "ipod.shuffle.gen1", "ipod.shuffle.gen2", "ipod.shuffle.gen3",
        "ipod.shuffle.gen4", "ipod.touch",
        "flipphone", "flipphone.fill",
        "candybarphone", "candybarphone.fill",
        "apps.iphone", "apps.iphone.fill",
        "apps.iphone.badge.plus", "apps.iphone.badge.plus.fill",
        "apps.ipad", "apps.ipad.fill",
        "apps.ipad.landscape", "apps.ipad.landscape.fill",
        "homepod", "homepod.fill",
        "homepod.2", "homepod.2.fill",
        "homepod.and.appletv", "homepod.and.appletv.fill",
        "homepod.2.and.appletv", "homepod.2.and.appletv.fill",
        "hometheater",
        "appletv", "appletv.fill",
        "airpods",
        "airpod.right", "airpod.left",
        "airpodspro",
        "airpodpro.right", "airpodpro.left",
        "airpods.gen3",
        "airpod.gen3.right", "airpod.gen3.left",
        "airpods.chargingcase.wireless", "airpods.chargingcase.wireless.fill",
        "airpods.chargingcase", "airpods.chargingcase.fill",
        "airpodspro.chargingcase.wireless", "airpodspro.chargingcase.wireless.fill",
        "airpod.gen3.chargingcase.wireless", "airpod.gen3.chargingcase.wireless.fill",
        "beats.earphones",
        "beats.headphones", "beats.headphones.fill",
        "beats.powerbeats", "beats.powerbeats.right", "beats.powerbeats.left",
        "beats.powerbeatspro", "beats.powerbeatspro.right", "beats.powerbeatspro.left",
        "beats.fitpro", "beats.fitpro.chargingcase", "beats.fitpro.chargingcase.fill",
        "beats.studiobuds", "beats.studiobuds.chargingcase", "beats.studiobuds.chargingcase.fill",
        "headphones", "headphones.circle", "headphones.circle.fill",
        "headphones.fill",
        "earbuds", "earbuds.case", "earbuds.case.fill",
        "earbuds.2", "earbuds.2.case", "earbuds.2.case.fill",
        "ear.and.waveform",
        "ear.badge.checkmark", "ear.trianglebadge.exclamationmark",
        "ear.fill", "ear.badge.checkmark.fill", "ear.trianglebadge.exclamationmark.fill",
        "hearingdevice.ear",
        "applewatch",
        "applewatch.watchface",
        "exclamationmark.applewatch",
        "lock.applewatch",
        "pin.applewatch",
        "play.applewatch",
        "checkmark.applewatch",
        "xmark.applewatch",
        "questionmark.applewatch",
        "bolt.applewatch",
        "bandage", "bandage.fill",
        "bed.double", "bed.double.fill",
        "bed.double.circle", "bed.double.circle.fill",
        "alarm", "alarm.fill",
        "alarm.waves.left.and.right", "alarm.waves.left.and.right.fill",
        "stopwatch", "stopwatch.fill",
        "timer", "timer.square",
        "gamecontroller", "gamecontroller.fill",
        "paintpalette", "paintpalette.fill",
        "swatchpalette", "swatchpalette.fill",
        "camera", "camera.fill",
        "camera.circle", "camera.circle.fill",
        "camera.shutter.button", "camera.shutter.button.fill",
        "camera.badge.ellipsis", "camera.fill.badge.ellipsis",
        "arrow.triangle.2.circlepath.camera", "arrow.triangle.2.circlepath.camera.fill",
        "camera.on.rectangle", "camera.on.rectangle.fill",
        "mic", "mic.fill",
        "mic.circle", "mic.circle.fill",
        "mic.square", "mic.square.fill",
        "mic.slash", "mic.slash.fill",
        "mic.slash.circle", "mic.slash.circle.fill",
        "mic.badge.plus", "mic.fill.badge.plus",
        "video", "video.fill",
        "video.circle", "video.circle.fill",
        "video.slash", "video.slash.fill",
        "video.badge.plus", "video.fill.badge.plus",
        "video.badge.checkmark", "video.fill.badge.checkmark",
        "arrow.up.right.video", "arrow.up.right.video.fill",
        "arrow.down.left.video", "arrow.down.left.video.fill",
        "questionmark.video", "questionmark.video.fill",
        "envelope", "envelope.fill",
        "envelope.circle", "envelope.circle.fill",
        "envelope.open", "envelope.open.fill",
        "envelope.badge", "envelope.fill.badge",
        "paperplane", "paperplane.fill",
        "paperplane.circle", "paperplane.circle.fill",
        "tray", "tray.fill",
        "tray.circle", "tray.circle.fill",
        "tray.full", "tray.full.fill",
        "tray.and.arrow.up", "tray.and.arrow.up.fill",
        "tray.and.arrow.down", "tray.and.arrow.down.fill",
        "tray.2", "tray.2.fill",
        "internaldrive", "internaldrive.fill",
        "externaldrive", "externaldrive.fill",
        "externaldrive.badge.plus", "externaldrive.fill.badge.plus",
        "externaldrive.badge.minus", "externaldrive.fill.badge.minus",
        "externaldrive.badge.checkmark", "externaldrive.fill.badge.checkmark",
        "externaldrive.badge.xmark", "externaldrive.fill.badge.xmark",
        "externaldrive.badge.person.crop", "externaldrive.fill.badge.person.crop",
        "externaldrive.badge.timemachine", "externaldrive.fill.badge.timemachine",
        "externaldrive.badge.icloud", "externaldrive.fill.badge.icloud",
        "externaldrive.badge.wifi", "externaldrive.fill.badge.wifi",
        "externaldrive.trianglebadge.exclamationmark", "externaldrive.fill.trianglebadge.exclamationmark",
        "archivebox", "archivebox.fill",
        "archivebox.circle", "archivebox.circle.fill",
        "doc", "doc.fill",
        "doc.circle", "doc.circle.fill",
        "doc.badge.plus", "doc.fill.badge.plus",
        "doc.badge.arrow.up", "doc.badge.arrow.up.fill",
        "doc.badge.ellipsis", "doc.fill.badge.ellipsis",
        "doc.badge.gearshape", "doc.badge.gearshape.fill",
        "doc.text", "doc.text.fill",
        "doc.zipper",
        "doc.on.doc", "doc.on.doc.fill",
        "doc.on.clipboard", "doc.on.clipboard.fill",
        "arrow.right.doc.on.clipboard",
        "arrow.up.doc.on.clipboard",
        "arrow.triangle.2.circlepath.doc.on.clipboard",
        "doc.richtext", "doc.richtext.fill",
        "doc.plaintext", "doc.plaintext.fill",
        "doc.append", "doc.append.fill",
        "doc.text.below.ecg", "doc.text.below.ecg.fill",
        "chart.bar.doc.horizontal",
        "list.bullet.rectangle", "list.bullet.rectangle.fill",
        "terminal", "terminal.fill",
        "note", "note.text",
        "note.text.badge.plus",
        "calendar", "calendar.circle", "calendar.circle.fill",
        "calendar.badge.plus", "calendar.badge.minus",
        "calendar.badge.clock", "calendar.badge.exclamationmark",
        "textformat.size",
        "textformat", "textformat.alt",
        "textformat.superscript", "textformat.subscript",
        "textformat.size.smaller", "textformat.size.larger",
        "textformat.abc", "textformat.abc.dottedunderline",
        "bold", "italic", "underline",
        "strikethrough",
        "shadow",
        "bold.italic.underline",
        "bold.underline",
        "view.2d", "view.3d",
        "selection.pin.in.out",
        "fx", "fx.magnifyingglass",
        "colorpicker", "colorpicker.fill",
        "wand.and.rays", "wand.and.rays.inverse",
        "wand.and.stars", "wand.and.stars.inverse",
        "crop", "crop.rotate",
        "aspectratio", "aspectratio.fill",
        "skew",
        "perspective",
        "checkerboard.rectangle",
        "camera.metering.none",
        "camera.metering.partial",
        "camera.metering.center.weighted",
        "camera.metering.center.weighted.average",
        "camera.metering.multispot",
        "camera.metering.average",
        "square.stack.3d.up", "square.stack.3d.up.fill",
        "square.stack.3d.up.badge.a", "square.stack.3d.up.badge.a.fill",
        "square.stack.3d.up.slash", "square.stack.3d.up.slash.fill",
        "square.stack.3d.forward.fill", "square.stack.3d.up.forward",
        "square.stack.3d.up.forward.fill",
        "square.stack.3d.backward.fill", "square.stack.3d.up.backward",
        "square.stack.3d.up.backward.fill",
        "livephoto", "livephoto.slash",
        "livephoto.badge.a",
        "livephoto.play",
        "scope", "scope.display",
        "hand.thumbsup", "hand.thumbsup.fill",
        "hand.thumbsdown", "hand.thumbsdown.fill",
        "hand.point.up.left", "hand.point.up.left.fill",
        "hand.point.up", "hand.point.up.fill",
        "hand.point.up.braille", "hand.point.up.braille.fill",
        "hand.point.down", "hand.point.down.fill",
        "hand.point.left", "hand.point.left.fill",
        "hand.point.right", "hand.point.right.fill",
        "hand.wave", "hand.wave.fill",
        "hand.tap", "hand.tap.fill",
        "hands.clap", "hands.clap.fill",
        "hands.sparkles", "hands.sparkles.fill",

        // MARK: - Connectivity & Sharing (60+)
        "wifi", "wifi.circle", "wifi.circle.fill",
        "wifi.square", "wifi.square.fill",
        "wifi.slash",
        "wifi.exclamationmark",
        "dot.radiowaves.left.and.right",
        "dot.radiowaves.right",
        "dot.radiowaves.forward",
        "dot.radiowaves.forward.slash",
        "wave.3.left", "wave.3.left.circle", "wave.3.left.circle.fill",
        "wave.3.right", "wave.3.right.circle", "wave.3.right.circle.fill",
        "wave.3.backward", "wave.3.backward.circle", "wave.3.backward.circle.fill",
        "wave.3.forward", "wave.3.forward.circle", "wave.3.forward.circle.fill",
        "antenna.radiowaves.left.and.right",
        "personalhotspot", "personalhotspot.circle", "personalhotspot.circle.fill",
        "network",
        "network.badge.shield.half.filled",
        "globe", "globe.fill",
        "globe.americas", "globe.americas.fill",
        "globe.europe.africa", "globe.europe.africa.fill",
        "globe.asia.australia", "globe.asia.australia.fill",
        "globe.central.south.asia", "globe.central.south.asia.fill",
        "network.badge.shield.half.filled",
        "bolt.horizontal", "bolt.horizontal.fill",
        "bolt.horizontal.circle", "bolt.horizontal.circle.fill",
        "icloud", "icloud.fill",
        "icloud.circle", "icloud.circle.fill",
        "icloud.square", "icloud.square.fill",
        "icloud.slash", "icloud.slash.fill",
        "icloud.and.arrow.up", "icloud.and.arrow.up.fill",
        "icloud.and.arrow.down", "icloud.and.arrow.down.fill",
        "icloud.badge.arrow.down", "icloud.badge.arrow.down.fill",
        "exclamationmark.icloud", "exclamationmark.icloud.fill",
        "xmark.icloud", "xmark.icloud.fill",
        "link.icloud", "link.icloud.fill",
        "person.icloud", "person.icloud.fill",
        "checkmark.icloud", "checkmark.icloud.fill",
        "arrow.clockwise.icloud", "arrow.clockwise.icloud.fill",
        "arrow.counterclockwise.icloud", "arrow.counterclockwise.icloud.fill",
        "icloud.badge.person.crop", "icloud.badge.person.crop.fill",
        "icloud.badge.xmark",
        "link", "link.fill",
        "link.circle", "link.circle.fill",
        "link.badge.plus",
        "doc.on.clipboard", "doc.on.clipboard.fill",
        "arrow.right.doc.on.clipboard",
        "arrow.up.doc.on.clipboard",
        "arrow.triangle.2.circlepath.doc.on.clipboard",
        "clipboard", "clipboard.fill",
        "list.bullet.clipboard", "list.bullet.clipboard.fill",
        "pencil.and.list.clipboard",
        "scroll", "scroll.fill",
        "envelope", "envelope.fill",
        "envelope.circle", "envelope.circle.fill",
        "envelope.open", "envelope.open.fill",
        "envelope.badge", "envelope.fill.badge",
        "envelope.badge.shield.half.filled", "envelope.badge.shield.half.filled.fill",
        "mail.stack", "mail.stack.fill",
        "mail", "mail.fill",
        "mail.and.text.magnifyingglass",
        "rectangle.and.pencil.and.ellipsis",
        "pencil", "pencil.circle", "pencil.circle.fill",
        "pencil.slash",
        "square.and.pencil", "square.and.pencil.circle", "square.and.pencil.circle.fill",
        "pencil.and.outline",
        "pencil.tip", "pencil.tip.crop.circle",
        "pencil.tip.crop.circle.badge.plus", "pencil.tip.crop.circle.badge.minus",
        "pencil.tip.crop.circle.badge.arrow.forward",
        "lasso", "lasso.and.sparkles",
        "trash", "trash.fill",
        "trash.circle", "trash.circle.fill",
        "trash.square", "trash.square.fill",
        "trash.slash", "trash.slash.fill",
        "trash.slash.circle", "trash.slash.circle.fill",
        "trash.slash.square", "trash.slash.square.fill",
        "folder", "folder.fill",
        "folder.circle", "folder.circle.fill",
        "folder.badge.plus", "folder.fill.badge.plus",
        "folder.badge.minus", "folder.fill.badge.minus",
        "folder.badge.person.crop", "folder.fill.badge.person.crop",
        "folder.badge.gear", "folder.fill.badge.gear",
        "folder.badge.questionmark", "folder.fill.badge.questionmark",
        "person.crop.folder", "person.crop.folder.fill",
        "house", "house.fill",
        "house.circle", "house.circle.fill",
        "house.and.flag", "house.and.flag.fill",
        "house.and.flag.circle", "house.and.flag.circle.fill",
        "music.note", "music.note.list",
        "music.quarternote.3",
        "music.mic",
        "music.mic.circle", "music.mic.circle.fill",

        // MARK: - Commerce & Finance (40+)
        "creditcard", "creditcard.fill",
        "creditcard.circle", "creditcard.circle.fill",
        "creditcard.and.123", "creditcard.and.123.fill",
        "creditcard.trianglebadge.exclamationmark", "creditcard.trianglebadge.exclamationmark.fill",
        "giftcard", "giftcard.fill",
        "wallet.pass", "wallet.pass.fill",
        "wallet.bifold", "wallet.bifold.fill",
        "dollarsign", "dollarsign.circle", "dollarsign.circle.fill", "dollarsign.square", "dollarsign.square.fill",
        "centsign", "centsign.circle", "centsign.circle.fill", "centsign.square", "centsign.square.fill",
        "yensign", "yensign.circle", "yensign.circle.fill", "yensign.square", "yensign.square.fill",
        "sterlingsign", "sterlingsign.circle", "sterlingsign.circle.fill", "sterlingsign.square", "sterlingsign.square.fill",
        "francsign", "francsign.circle", "francsign.circle.fill", "francsign.square", "francsign.square.fill",
        "florinsign", "florinsign.circle", "florinsign.circle.fill", "florinsign.square", "florinsign.square.fill",
        "turkishlirasign", "turkishlirasign.circle", "turkishlirasign.circle.fill", "turkishlirasign.square", "turkishlirasign.square.fill",
        "rublesign", "rublesign.circle", "rublesign.circle.fill", "rublesign.square", "rublesign.square.fill",
        "eurosign", "eurosign.circle", "eurosign.circle.fill", "eurosign.square", "eurosign.square.fill",
        "dongsign", "dongsign.circle", "dongsign.circle.fill", "dongsign.square", "dongsign.square.fill",
        "indianrupeesign", "indianrupeesign.circle", "indianrupeesign.circle.fill", "indianrupeesign.square", "indianrupeesign.square.fill",
        "tengesign", "tengesign.circle", "tengesign.circle.fill", "tengesign.square", "tengesign.square.fill",
        "pesetasign", "pesetasign.circle", "pesetasign.circle.fill", "pesetasign.square", "pesetasign.square.fill",
        "pesosign", "pesosign.circle", "pesosign.circle.fill", "pesosign.square", "pesosign.square.fill",
        "kipsign", "kipsign.circle", "kipsign.circle.fill", "kipsign.square", "kipsign.square.fill",
        "wonsign", "wonsign.circle", "wonsign.circle.fill", "wonsign.square", "wonsign.square.fill",
        "lirasign", "lirasign.circle", "lirasign.circle.fill", "lirasign.square", "lirasign.square.fill",
        "australsign", "australsign.circle", "australsign.circle.fill", "australsign.square", "australsign.square.fill",
        "hryvniasign", "hryvniasign.circle", "hryvniasign.circle.fill", "hryvniasign.square", "hryvniasign.square.fill",
        "nairasign", "nairasign.circle", "nairasign.circle.fill", "nairasign.square", "nairasign.square.fill",
        "guaranisign", "guaranisign.circle", "guaranisign.circle.fill", "guaranisign.square", "guaranisign.square.fill",
        "coloncurrency.sign", "coloncurrency.sign.circle", "coloncurrency.sign.circle.fill", "coloncurrency.sign.square", "coloncurrency.sign.square.fill",
        "cedisign", "cedisign.circle", "cedisign.circle.fill", "cedisign.square", "cedisign.square.fill",
        "cruzeirosign", "cruzeirosign.circle", "cruzeirosign.circle.fill", "cruzeirosign.square", "cruzeirosign.square.fill",
        "tugriksign", "tugriksign.circle", "tugriksign.circle.fill", "tugriksign.square", "tugriksign.square.fill",
        "millsign", "millsign.circle", "millsign.circle.fill", "millsign.square", "millsign.square.fill",
        "shekelsign", "shekelsign.circle", "shekelsign.circle.fill", "shekelsign.square", "shekelsign.square.fill",
        "manatsign", "manatsign.circle", "manatsign.circle.fill", "manatsign.square", "manatsign.square.fill",
        "bahtsign", "bahtsign.circle", "bahtsign.circle.fill", "bahtsign.square", "bahtsign.square.fill",
        "larisign", "larisign.circle", "larisign.circle.fill", "larisign.square", "larisign.square.fill",
        "bitcoinsign", "bitcoinsign.circle", "bitcoinsign.circle.fill", "bitcoinsign.square", "bitcoinsign.square.fill",
        "brazilianrealsign", "brazilianrealsign.circle", "brazilianrealsign.circle.fill", "brazilianrealsign.square", "brazilianrealsign.square.fill",
        "chineseyuanrenminbisign", "chineseyuanrenminbisign.circle", "chineseyuanrenminbisign.circle.fill", "chineseyuanrenminbisign.square", "chineseyuanrenminbisign.square.fill",
        "singaporedollarsign", "singaporedollarsign.circle", "singaporedollarsign.circle.fill", "singaporedollarsign.square", "singaporedollarsign.square.fill",
        "polishzlotysign", "polishzlotysign.circle", "polishzlotysign.circle.fill", "polishzlotysign.square", "polishzlotysign.square.fill",
        "norwegiankronesign", "norwegiankronesign.circle", "norwegiankronesign.circle.fill", "norwegiankronesign.square", "norwegiankronesign.square.fill",
        "swedishkronasign", "swedishkronasign.circle", "swedishkronasign.circle.fill", "swedishkronasign.square", "swedishkronasign.square.fill",
        "danishkronesign", "danishkronesign.circle", "danishkronesign.circle.fill", "danishkronesign.square", "danishkronesign.square.fill",
        "saudiriyalsign", "saudiriyalsign.circle", "saudiriyalsign.circle.fill", "saudiriyalsign.square", "saudiriyalsign.square.fill",
        "malaysianringgitsign", "malaysianringgitsign.circle", "malaysianringgitsign.circle.fill", "malaysianringgitsign.square", "malaysianringgitsign.square.fill",
        "cart", "cart.fill",
        "cart.circle", "cart.circle.fill",
        "cart.badge.plus", "cart.fill.badge.plus",
        "cart.badge.minus", "cart.fill.badge.minus",
        "cart.badge.questionmark", "cart.fill.badge.questionmark",
        "basket", "basket.fill",
        "bag", "bag.fill",
        "bag.circle", "bag.circle.fill",
        "bag.badge.plus", "bag.fill.badge.plus",
        "bag.badge.minus", "bag.fill.badge.minus",
        "bag.badge.questionmark", "bag.fill.badge.questionmark",
        "handbag", "handbag.fill",
        "handbag.circle", "handbag.circle.fill",
        "purchased", "purchased.circle", "purchased.circle.fill",
        "banknote", "banknote.fill",
        "banknote.haptic.arrow.down",
        "banknote.haptic.arrow.up",

        // MARK: - Weather & Nature (50+)
        "sun.min", "sun.min.fill",
        "sun.max", "sun.max.fill",
        "sun.max.circle", "sun.max.circle.fill",
        "sun.max.trianglebadge.exclamationmark", "sun.max.trianglebadge.exclamationmark.fill",
        "sun.lefthalf.fill",
        "sun.righthalf.fill",
        "sun.and.horizon", "sun.and.horizon.fill",
        "sun.and.horizon.circle", "sun.and.horizon.circle.fill",
        "sunrise", "sunrise.fill",
        "sunrise.circle", "sunrise.circle.fill",
        "sunset", "sunset.fill",
        "sunset.circle", "sunset.circle.fill",
        "sun.dust", "sun.dust.fill",
        "sun.haze", "sun.haze.fill",
        "sun.rain", "sun.rain.fill",
        "sun.snow", "sun.snow.fill",
        "cloud.sun", "cloud.sun.fill",
        "cloud.sun.rain", "cloud.sun.rain.fill",
        "cloud.sun.bolt", "cloud.sun.bolt.fill",
        "moon", "moon.fill",
        "moon.circle", "moon.circle.fill",
        "moon.haze", "moon.haze.fill",
        "moon.stars", "moon.stars.fill",
        "moon.stars.circle", "moon.stars.circle.fill",
        "cloud.moon", "cloud.moon.fill",
        "cloud.moon.rain", "cloud.moon.rain.fill",
        "cloud.moon.bolt", "cloud.moon.bolt.fill",
        "sparkles",
        "sparkle",
        "cloud", "cloud.fill",
        "cloud.circle", "cloud.circle.fill",
        "cloud.drizzle", "cloud.drizzle.fill",
        "cloud.rain", "cloud.rain.fill",
        "cloud.heavyrain", "cloud.heavyrain.fill",
        "cloud.fog", "cloud.fog.fill",
        "cloud.hail", "cloud.hail.fill",
        "cloud.snow", "cloud.snow.fill",
        "cloud.sleet", "cloud.sleet.fill",
        "cloud.bolt", "cloud.bolt.fill",
        "cloud.bolt.rain", "cloud.bolt.rain.fill",
        "cloud.sun", "cloud.sun.fill",
        "cloud.sun.rain", "cloud.sun.rain.fill",
        "cloud.sun.bolt", "cloud.sun.bolt.fill",
        "cloud.moon", "cloud.moon.fill",
        "cloud.moon.rain", "cloud.moon.rain.fill",
        "cloud.moon.bolt", "cloud.moon.bolt.fill",
        "smoke", "smoke.fill",
        "smoke.circle", "smoke.circle.fill",
        "wind",
        "wind.circle", "wind.circle.fill",
        "wind.snow", "wind.snow.fill",
        "snowflake",
        "snowflake.circle", "snowflake.circle.fill",
        "snowflake.slash",
        "tornado", "tornado.circle", "tornado.circle.fill",
        "tropicalstorm", "tropicalstorm.circle", "tropicalstorm.circle.fill",
        "hurricane", "hurricane.circle", "hurricane.circle.fill",
        "thermometer.sun", "thermometer.sun.fill",
        "thermometer.snowflake", "thermometer.snowflake.fill",
        "thermometer.low",
        "thermometer.medium",
        "thermometer.high",
        "thermometer.medium.slash",
        "thermometer.sun", "thermometer.sun.fill",
        "thermometer.variable",
        "rainbow", "rainbow.circle", "rainbow.circle.fill",
        "bolt", "bolt.fill",
        "bolt.circle", "bolt.circle.fill",
        "bolt.square", "bolt.square.fill",
        "bolt.slash", "bolt.slash.fill",
        "bolt.slash.circle", "bolt.slash.circle.fill",
        "bolt.badge.a", "bolt.badge.a.fill",
        "bolt.horizontal", "bolt.horizontal.fill",
        "bolt.horizontal.circle", "bolt.horizontal.circle.fill",

        // MARK: - Sports & Fitness (40+)
        "baseball", "baseball.fill",
        "baseball.circle", "baseball.circle.fill",
        "basketball", "basketball.fill",
        "basketball.circle", "basketball.circle.fill",
        "football", "football.fill",
        "football.circle", "football.circle.fill",
        "soccerball", "soccerball.fill",
        "soccerball.circle", "soccerball.circle.fill",
        "tennis.racket", "tennis.racket.fill",
        "tennis.racket.circle", "tennis.racket.circle.fill",
        "hockey.puck", "hockey.puck.fill",
        "hockey.puck.circle", "hockey.puck.circle.fill",
        "cricket.ball", "cricket.ball.fill",
        "cricket.ball.circle", "cricket.ball.circle.fill",
        "volleyball", "volleyball.fill",
        "volleyball.circle", "volleyball.circle.fill",
        "american.football", "american.football.fill",
        "american.football.circle", "american.football.circle.fill",
        "rugbyball", "rugbyball.fill",
        "rugbyball.circle", "rugbyball.circle.fill",
        "golf.flag", "golf.flag.fill",
        "golf.flag.circle", "golf.flag.circle.fill",
        "flag.filled.and.flag.crossed",
        "flag.2.crossed", "flag.2.crossed.fill",
        "flag.2.crossed.circle", "flag.2.crossed.circle.fill",
        "flag.checkered", "flag.checkered.circle", "flag.checkered.circle.fill",
        "flag.checkered.2.crossed",
        "figure.walk", "figure.walk.circle", "figure.walk.circle.fill",
        "figure.walk.arrival", "figure.walk.arrival.fill",
        "figure.walk.departure", "figure.walk.departure.fill",
        "figure.walk.motion",
        "figure.walk.diamond", "figure.walk.diamond.fill",
        "figure.run", "figure.run.circle", "figure.run.circle.fill",
        "figure.badminton",
        "figure.barre",
        "figure.baseball",
        "figure.basketball",
        "figure.bowling",
        "figure.boxing",
        "figure.climbing",
        "figure.cooldown",
        "figure.core.training",
        "figure.cricket",
        "figure.skiing.crosscountry",
        "figure.curling",
        "figure.dance",
        "figure.disc.sports",
        "figure.skiing.downhill",
        "figure.elliptical",
        "figure.equestrian.sports",
        "figure.fencing",
        "figure.fishing",
        "figure.flexibility",
        "figure.strengthtraining.functional",
        "figure.golf",
        "figure.gymnastics",
        "figure.hand.cycling",
        "figure.hiking",
        "figure.hockey",
        "figure.hunting",
        "figure.indoor.cycle",
        "figure.jumprope",
        "figure.kickboxing",
        "figure.lacrosse",
        "figure.martial.arts",
        "figure.mind.and.body",
        "figure.mixed.cardio",
        "figure.open.water.swim",
        "figure.outdoor.cycle",
        "figure.ocean.sports",
        "figure.pickleball",
        "figure.pilates",
        "figure.play",
        "figure.pool.swim",
        "figure.racquetball",
        "figure.rolling",
        "figure.rower",
        "figure.rugby",
        "figure.run.treadmill",
        "figure.sailing",
        "figure.skating",
        "figure.skiing",
        "figure.snowboarding",
        "figure.soccer",
        "figure.socialdance",
        "figure.softball",
        "figure.squash",
        "figure.stair.stepper",
        "figure.stairs",
        "figure.step.training",
        "figure.surfing",
        "figure.table.tennis",
        "figure.taichi",
        "figure.tennis",
        "figure.track.and.field",
        "figure.strengthtraining.traditional",
        "figure.volleyball",
        "figure.water.fitness",
        "figure.waterpolo",
        "figure.wrestling",
        "figure.yoga",

        // MARK: - Health & Medical (30+)
        "heart", "heart.fill",
        "heart.circle", "heart.circle.fill",
        "heart.square", "heart.square.fill",
        "heart.rectangle", "heart.rectangle.fill",
        "heart.slash", "heart.slash.fill",
        "heart.slash.circle", "heart.slash.circle.fill",
        "heart.slash.fill.circle.fill",
        "heart.text.square", "heart.text.square.fill",
        "bolt.heart", "bolt.heart.fill",
        "bolt.heart.circle", "bolt.heart.circle.fill",
        "bandage", "bandage.fill",
        "syringe", "syringe.fill",
        "pills", "pills.fill",
        "pills.circle", "pills.circle.fill",
        "cross", "cross.fill",
        "cross.circle", "cross.circle.fill",
        "eye", "eye.fill",
        "eye.circle", "eye.circle.fill",
        "eye.square", "eye.square.fill",
        "eye.slash", "eye.slash.fill",
        "eye.slash.circle", "eye.slash.circle.fill",
        "eye.trianglebadge.exclamationmark", "eye.trianglebadge.exclamationmark.fill",
        "ear", "ear.fill",
        "ear.badge.checkmark", "ear.badge.checkmark.fill",
        "ear.trianglebadge.exclamationmark", "ear.trianglebadge.exclamationmark.fill",
        "ear.and.waveform",
        "hearingdevice.ear",
        "lungs", "lungs.fill",
        "stethoscope", "stethoscope.circle", "stethoscope.circle.fill",
        "facemask", "facemask.fill",
        "crown", "crown.fill",
        "tooth", "tooth.fill",
        "brain", "brain.fill",
        "brain.head.profile", "brain.head.profile.fill",

        // MARK: - Food & Drink (40+)
        "leaf", "leaf.fill",
        "leaf.circle", "leaf.circle.fill",
        "leaf.arrow.triangle.circlepath",
        "carrot", "carrot.fill",
        "carrot.circle", "carrot.circle.fill",
        "apple.logo",
        "apple.meditate", "apple.meditate.fill",
        "apple.meditate.circle", "apple.meditate.circle.fill",
        "fork.knife", "fork.knife.circle", "fork.knife.circle.fill",
        "cup.and.saucer", "cup.and.saucer.fill",
        "mug", "mug.fill",
        "takeoutbag.and.cup.and.straw", "takeoutbag.and.cup.and.straw.fill",
        "wineglass", "wineglass.fill",
        "waterbottle", "waterbottle.fill",
        "birthday.cake", "birthday.cake.fill",
        "carrot", "carrot.fill",
        "fork.knife",
        "frying.pan", "frying.pan.fill",
        "cooktop", "cooktop.fill",
        "oven", "oven.fill",
        "microwave", "microwave.fill",
        "refrigerator", "refrigerator.fill",
        "dishwasher", "dishwasher.fill",
        "washer", "washer.fill",
        "dryer", "dryer.fill",
        "toaster", "toaster.fill",
        "popcorn", "popcorn.fill",
        "popcorn.circle", "popcorn.circle.fill",
        "bubble.tea", "bubble.tea.fill",
        "bubble.tea.circle", "bubble.tea.circle.fill",
        "mug", "mug.fill",
        "mug.circle", "mug.circle.fill",
        "wineglass", "wineglass.fill",
        "wineglass.circle", "wineglass.circle.fill",
        "waterbottle", "waterbottle.fill",
        "waterbottle.circle", "waterbottle.circle.fill",
        "carton", "carton.fill",
        "carton.circle", "carton.circle.fill",
        "basket", "basket.fill",
        "takeoutbag.and.cup.and.straw", "takeoutbag.and.cup.and.straw.fill",
        "bag", "bag.fill",
        "bag.circle", "bag.circle.fill",
        "pianokeys", "pianokeys.inverse",
        "guitar", "guitars",
        "guitar.fill",
        "vinyl.record", "vinyl.record.fill",
        "vinyl.record.circle", "vinyl.record.circle.fill",
        "movieclapper", "movieclapper.fill",
        "theatermasks", "theatermasks.fill",
        "theatermasks.circle", "theatermasks.circle.fill",
        "ticket", "ticket.fill",
        "paintbrush", "paintbrush.fill",
        "paintbrush.pointed", "paintbrush.pointed.fill",
        "level", "level.fill",
        "wrench.adjustable", "wrench.adjustable.fill",
        "hammer", "hammer.fill",
        "hammer.circle", "hammer.circle.fill",
        "screwdriver", "screwdriver.fill",
        "screw", "screw.fill",
        "key", "key.fill",
        "key.horizontal", "key.horizontal.fill",
        "key.radiowaves.forward", "key.radiowaves.forward.fill",
        "key.radiowaves.forward.slash", "key.radiowaves.forward.slash.fill",
        "lock", "lock.fill",
        "lock.circle", "lock.circle.fill",
        "lock.square", "lock.square.fill",
        "lock.square.stack", "lock.square.stack.fill",
        "lock.rectangle", "lock.rectangle.fill",
        "lock.rectangle.stack", "lock.rectangle.stack.fill",
        "lock.shield", "lock.shield.fill",
        "lock.slash", "lock.slash.fill",
        "lock.slash.circle", "lock.slash.circle.fill",
        "lock.open", "lock.open.fill",
        "lock.open.trianglebadge.exclamationmark", "lock.open.trianglebadge.exclamationmark.fill",
        "lock.rotation", "lock.rotation.open",

        // MARK: - Transportation (50+)
        "car", "car.fill",
        "car.circle", "car.circle.fill",
        "car.front.waves.left", "car.front.waves.left.fill",
        "car.front.waves.right", "car.front.waves.right.fill",
        "car.side", "car.side.fill",
        "car.side.front.open", "car.side.front.open.fill",
        "car.side.rear.open", "car.side.rear.open.fill",
        "car.side.air.circulate", "car.side.air.circulate.fill",
        "car.side.air.fresh", "car.side.air.fresh.fill",
        "car.side.and.exclamationmark", "car.side.and.exclamationmark.fill",
        "car.side.arrowtriangle.up", "car.side.arrowtriangle.up.fill",
        "car.side.arrowtriangle.down", "car.side.arrowtriangle.down.fill",
        "suv.side", "suv.side.fill",
        "suv.side.front.open", "suv.side.front.open.fill",
        "suv.side.rear.open", "suv.side.rear.open.fill",
        "suv.side.air.circulate", "suv.side.air.circulate.fill",
        "suv.side.air.fresh", "suv.side.air.fresh.fill",
        "suv.side.and.exclamationmark", "suv.side.and.exclamationmark.fill",
        "suv.side.arrowtriangle.up", "suv.side.arrowtriangle.up.fill",
        "suv.side.arrowtriangle.down", "suv.side.arrowtriangle.down.fill",
        "car.2", "car.2.fill",
        "bus", "bus.fill",
        "bus.doubledecker", "bus.doubledecker.fill",
        "bus.side", "bus.side.fill",
        "tram", "tram.fill",
        "tram.circle", "tram.circle.fill",
        "tram.tunnel.fill",
        "cablecar", "cablecar.fill",
        "train.side.front.car", "train.side.middle.car", "train.side.rear.car",
        "ferry", "ferry.fill",
        "sailboat", "sailboat.fill",
        "sailboat.circle", "sailboat.circle.fill",
        "airplane", "airplane.fill",
        "airplane.circle", "airplane.circle.fill",
        "airplane.arrival", "airplane.arrival.fill",
        "airplane.departure", "airplane.departure.fill",
        "scooter",
        "bicycle", "bicycle.circle", "bicycle.circle.fill",
        "motorcycle", "motorcycle.fill",
        "moped", "moped.fill",
        "gondola", "gondola.fill",
        "gondola.circle", "gondola.circle.fill",
        "tram.fill.tunnel",
        "fuel.pump", "fuel.pump.fill",
        "fuel.pump.circle", "fuel.pump.circle.fill",
        "fuel.pump.slash", "fuel.pump.slash.fill",
        "ev.charger", "ev.charger.fill",
        "ev.charger.slash", "ev.charger.slash.fill",
        "parkingsign", "parkingsign.circle", "parkingsign.circle.fill",
        "parkingsign.brakeshoes", "parkingsign.brakeshoes.fill",
        "parkingsign.brakeshoes.slash", "parkingsign.brakeshoes.slash.fill",
        "parkingsign.radiowaves.left.and.right", "parkingsign.radiowaves.left.and.right.fill",
        "parkingsign.radiowaves.left.and.right.slash", "parkingsign.radiowaves.left.and.right.slash.fill",
        "parkingsign.radiowaves.down", "parkingsign.radiowaves.down.fill",
        "parkingsign.radiowaves.down.slash", "parkingsign.radiowaves.down.slash.fill",
        "road.lanes", "road.lanes.fill",
        "steeringwheel", "steeringwheel.fill",
        "steeringwheel.circle", "steeringwheel.circle.fill",
        "steeringwheel.slash", "steeringwheel.slash.fill",
        "steeringwheel.and.key",
        "steeringwheel.and.lock",
        "steeringwheel.and.hands",
        "tirepressure",
        "exclamationmark.triangle",
        "charge.station", "charge.station.fill",

        // MARK: - Animals & Nature (30+)
        "pawprint", "pawprint.fill",
        "pawprint.circle", "pawprint.circle.fill",
        "bird", "bird.fill",
        "bird.circle", "bird.circle.fill",
        "fish", "fish.fill",
        "fish.circle", "fish.circle.fill",
        "tortoise", "tortoise.fill",
        "tortoise.circle", "tortoise.circle.fill",
        "hare", "hare.fill",
        "hare.circle", "hare.circle.fill",
        "ant", "ant.fill",
        "ant.circle", "ant.circle.fill",
        "ladybug", "ladybug.fill",
        "ladybug.circle", "ladybug.circle.fill",
        "leaf", "leaf.fill",
        "leaf.circle", "leaf.circle.fill",
        "leaf.arrow.triangle.circlepath",
        "fossil.shell", "fossil.shell.fill",
        "mountain.2", "mountain.2.fill",
        "mountain.2.circle", "mountain.2.circle.fill",
        "mountain.2.trianglebadge.exclamationmark", "mountain.2.trianglebadge.exclamationmark.fill",
        "tree", "tree.fill",
        "tree.circle", "tree.circle.fill",
        "firework",
        "laurel.leading", "laurel.trailing",
        "trophy", "trophy.fill",
        "trophy.circle", "trophy.circle.fill",
        "medal", "medal.fill",
        "rosette",
        "balloon", "balloon.fill",
        "balloon.circle", "balloon.circle.fill",
        "party.popper", "party.popper.fill",
        "ribbon", "ribbon.fill",
        "popcorn", "popcorn.fill",
        "popcorn.circle", "popcorn.circle.fill",

        // MARK: - Faces & People (30+)
        "face.smiling", "face.smiling.fill",
        "face.smiling.inverse",
        "face.dashed",
        "face.dashed.fill",
        "person", "person.fill",
        "person.circle", "person.circle.fill",
        "person.2", "person.2.fill",
        "person.2.circle", "person.2.circle.fill",
        "person.3", "person.3.fill",
        "person.3.sequence", "person.3.sequence.fill",
        "person.crop.circle", "person.crop.circle.fill",
        "person.crop.circle.badge.plus", "person.crop.circle.badge.plus.fill",
        "person.crop.circle.badge.minus", "person.crop.circle.badge.minus.fill",
        "person.crop.circle.badge.checkmark", "person.crop.circle.badge.checkmark.fill",
        "person.crop.circle.badge.xmark", "person.crop.circle.badge.xmark.fill",
        "person.crop.circle.badge.questionmark", "person.crop.circle.badge.questionmark.fill",
        "person.crop.circle.badge.exclamationmark", "person.crop.circle.badge.exclamationmark.fill",
        "person.crop.circle.badge.moon", "person.crop.circle.badge.moon.fill",
        "person.crop.circle.badge.clock", "person.crop.circle.badge.clock.fill",
        "person.crop.square", "person.crop.square.fill",
        "person.crop.artframe",
        "person.crop.rectangle.stack", "person.crop.rectangle.stack.fill",
        "person.2.crop.square.stack", "person.2.crop.square.stack.fill",
        "person.crop.rectangle", "person.crop.rectangle.fill",
        "person.and.background.dotted",
        "person.and.background.striped.horizontal",
        "person.fill.turn.down", "person.fill.turn.right", "person.fill.turn.left",
        "person.fill.checkmark", "person.fill.xmark", "person.fill.questionmark",
        "person.fill.badge.plus", "person.fill.badge.minus",
        "person.fill.badge.clock",
        "person.text.rectangle", "person.text.rectangle.fill",
        "person.and.arrow.left.and.arrow.right",
        "person.2.slash", "person.2.slash.fill",
        "person.2.badge.gearshape", "person.2.badge.gearshape.fill",
        "person.3.sequence", "person.3.sequence.fill",
        "person.wave.2", "person.wave.2.fill",
        "shareplay", "shareplay.slash",
        "person.line.dotted.person", "person.line.dotted.person.fill",
        "figure.stand", "figure.stand.line.dotted.figure.stand",
        "figure.walk", "figure.walk.circle", "figure.walk.circle.fill",
        "figure.run", "figure.run.circle", "figure.run.circle.fill",
        "figure.roll",
        "figure.wave", "figure.wave.circle", "figure.wave.circle.fill",
        "figure.fall", "figure.fall.circle", "figure.fall.circle.fill",

        // MARK: - Maps & Location (40+)
        "map", "map.fill",
        "map.circle", "map.circle.fill",
        "mappin", "mappin.fill",
        "mappin.circle", "mappin.circle.fill",
        "mappin.slash", "mappin.slash.fill",
        "mappin.and.ellipse",
        "map.circle", "map.circle.fill",
        "map.fill.and.flag.circle", "map.fill.and.flag.circle.fill",
        "location", "location.fill",
        "location.circle", "location.circle.fill",
        "location.slash", "location.slash.fill",
        "location.slash.circle", "location.slash.circle.fill",
        "location.north", "location.north.fill",
        "location.north.circle", "location.north.circle.fill",
        "location.north.line", "location.north.line.fill",
        "dot.arrowtriangles.up.right.down.left.circle",
        "location.viewfinder",
        "location.magnifyingglass",
        "location.fill.viewfinder",
        "compass", "compass.fill",
        "compass.circle", "compass.circle.fill",
        "compass.drawing",
        "scope",
        "scope.display",
        "scope.on.clipboard", "scope.on.clipboard.fill",
        "binoculars", "binoculars.fill",
        "eyeglasses",
        "sunglasses",
        "sunglasses.fill",
        "cpu", "cpu.fill",
        "memorychip", "memorychip.fill",
        "opticaldisc",
        "opticaldisc.fill",
        "opticaldiscdrive", "opticaldiscdrive.fill",
        "simcard", "simcard.fill",
        "simcard.2", "simcard.2.fill",
        "esim",
        "esim.fill",
        "sdcard", "sdcard.fill",
        "sdcard.circle", "sdcard.circle.fill",
        "scroll", "scroll.fill",
        "scroll.circle", "scroll.circle.fill",
        "newspaper", "newspaper.fill",
        "newspaper.circle", "newspaper.circle.fill",
        "note.text",
        "note.text.badge.plus",
        "calendar", "calendar.circle", "calendar.circle.fill",
        "calendar.badge.plus", "calendar.badge.minus",
        "calendar.badge.clock", "calendar.badge.exclamationmark",
        "calendar.day.timeline.leading",
        "calendar.day.timeline.left",
        "calendar.day.timeline.right",
        "calendar.day.timeline.trailing",
        "calendar.badge.checkmark",

        // MARK: - Text & Editing (40+)
        "character", "character.fill",
        "character.circle", "character.circle.fill",
        "character.square", "character.square.fill",
        "character.book.closed", "character.book.closed.fill",
        "character.textbox",
        "a.square", "a.square.fill",
        "b.square", "b.square.fill",
        "c.square", "c.square.fill",
        "d.square", "d.square.fill",
        "e.square", "e.square.fill",
        "f.square", "f.square.fill",
        "g.square", "g.square.fill",
        "h.square", "h.square.fill",
        "i.square", "i.square.fill",
        "j.square", "j.square.fill",
        "k.square", "k.square.fill",
        "l.square", "l.square.fill",
        "m.square", "m.square.fill",
        "n.square", "n.square.fill",
        "o.square", "o.square.fill",
        "p.square", "p.square.fill",
        "q.square", "q.square.fill",
        "r.square", "r.square.fill",
        "s.square", "s.square.fill",
        "t.square", "t.square.fill",
        "u.square", "u.square.fill",
        "v.square", "v.square.fill",
        "w.square", "w.square.fill",
        "x.square", "x.square.fill",
        "y.square", "y.square.fill",
        "z.square", "z.square.fill",
        "numbersign",
        "textformat", "textformat.alt",
        "textformat.size",
        "textformat.size.smaller", "textformat.size.larger",
        "textformat.superscript", "textformat.subscript",
        "textformat.abc", "textformat.abc.dottedunderline",
        "bold", "italic", "underline",
        "strikethrough",
        "bold.italic.underline",
        "bold.underline",
        "highlighter",
        "pencil.tip", "pencil.tip.crop.circle",
        "pencil.tip.crop.circle.badge.plus", "pencil.tip.crop.circle.badge.minus",
        "pencil.tip.crop.circle.badge.arrow.forward",
        "pencil.and.scribble",
        "lasso", "lasso.and.sparkles",
        "trash", "trash.fill",
        "trash.circle", "trash.circle.fill",
        "trash.slash", "trash.slash.fill",
        "trash.slash.circle", "trash.slash.circle.fill",
        "folder", "folder.fill",
        "folder.circle", "folder.circle.fill",
        "folder.badge.plus", "folder.fill.badge.plus",
        "folder.badge.minus", "folder.fill.badge.minus",
        "folder.badge.person.crop", "folder.fill.badge.person.crop",
        "folder.badge.gear", "folder.fill.badge.gear",
        "folder.badge.questionmark", "folder.fill.badge.questionmark",
        "paperplane", "paperplane.fill",
        "paperplane.circle", "paperplane.circle.fill",
        "tray", "tray.fill",
        "tray.circle", "tray.circle.fill",
        "tray.full", "tray.full.fill",
        "tray.and.arrow.up", "tray.and.arrow.up.fill",
        "tray.and.arrow.down", "tray.and.arrow.down.fill",
        "tray.2", "tray.2.fill",
        "internaldrive", "internaldrive.fill",
        "externaldrive", "externaldrive.fill",
        "archivebox", "archivebox.fill",
        "archivebox.circle", "archivebox.circle.fill",
        "doc", "doc.fill",
        "doc.circle", "doc.circle.fill",
        "doc.text", "doc.text.fill",
        "doc.zipper",
        "doc.on.doc", "doc.on.doc.fill",
        "doc.on.clipboard", "doc.on.clipboard.fill",
        "arrow.right.doc.on.clipboard",
        "arrow.up.doc.on.clipboard",
        "doc.richtext", "doc.richtext.fill",
        "doc.plaintext", "doc.plaintext.fill",
        "doc.append", "doc.append.fill",

        // MARK: - Development & Code (30+)
        "chevron.left.forwardslash.chevron.right",
        "chevron.left.forwardslash.chevron.right.circle",
        "chevron.left.forwardslash.chevron.right.circle.fill",
        "chevron.left.forwardslash.chevron.right.square",
        "chevron.left.forwardslash.chevron.right.square.fill",
        "number", "number.circle", "number.circle.fill",
        "number.square", "number.square.fill",
        "x.squareroot",
        "function", "function.circle", "function.circle.fill",
        "function.square", "function.square.fill",
        "fx", "fx.magnifyingglass",
        "sum", "sum.circle", "sum.circle.fill",
        "percent", "percent.circle", "percent.circle.fill",
        "percent.square", "percent.square.fill",
        "at", "at.circle", "at.circle.fill",
        "at.badge.plus", "at.badge.minus",
        "plusminus", "plusminus.circle", "plusminus.circle.fill",
        "minus.plus.batteryblock", "minus.plus.batteryblock.fill",
        "minus.forwardslash.plus",
        "plus.forwardslash.minus",
        "multiply", "multiply.circle", "multiply.circle.fill",
        "multiply.square", "multiply.square.fill",
        "divide", "divide.circle", "divide.circle.fill",
        "divide.square", "divide.square.fill",
        "equal", "equal.circle", "equal.circle.fill",
        "equal.square", "equal.square.fill",
        "lessthan", "lessthan.circle", "lessthan.circle.fill",
        "lessthan.square", "lessthan.square.fill",
        "greaterthan", "greaterthan.circle", "greaterthan.circle.fill",
        "greaterthan.square", "greaterthan.square.fill",
        "number.sign",
        "command", "command.circle", "command.circle.fill",
        "command.square", "command.square.fill",
        "option", "option.circle", "option.circle.fill",
        "option.square", "option.square.fill",
        "alt", "alt.circle", "alt.circle.fill",
        "alt.square", "alt.square.fill",
        "control", "control.circle", "control.circle.fill",
        "control.square", "control.square.fill",
        "delete.left", "delete.left.fill",
        "delete.left.square", "delete.left.square.fill",
        "delete.right", "delete.right.fill",
        "delete.right.square", "delete.right.square.fill",
        "clear", "clear.fill",
        "escape",
        "circle.bottomhalf.filled",
        "circle.tophalf.filled",
        "circle.lefthalf.filled",
        "circle.righthalf.filled",
        "circle.inset.filled",
        "smallcircle.filled.circle",
        "smallcircle.filled.circle.fill",
        "smallcircle.circle",
        "smallcircle.circle.fill",
        "target",
        "circle.dotted",
        "circle.dashed",
        "circle.badge.plus", "circle.badge.plus.fill",
        "circle.badge.minus", "circle.badge.minus.fill",
        "circle.badge.checkmark", "circle.badge.checkmark.fill",
        "circle.badge.xmark", "circle.badge.xmark.fill",
        "circle.badge.questionmark", "circle.badge.questionmark.fill",
        "circle.badge.exclamationmark", "circle.badge.exclamationmark.fill",
        "circle.badge.2", "circle.badge.2.fill",
        "circle.grid.2x2", "circle.grid.2x2.fill",
        "circle.grid.3x3", "circle.grid.3x3.fill",
        "circle.grid.cross", "circle.grid.cross.fill",
        "circle.hexagongrid", "circle.hexagongrid.fill",
        "circle.hexagonpath", "circle.hexagonpath.fill",
        "circle.fill.square.fill",
        "square.circle", "square.circle.fill",
        "square.fill.and.line.vertical.square.fill",
        "square.bottomhalf.filled",
        "square.tophalf.filled",
        "square.lefthalf.filled",
        "square.righthalf.filled",
        "square.inset.filled",
        "square.split.2x1", "square.split.2x1.fill",
        "square.split.1x2", "square.split.1x2.fill",
        "square.split.diagonal", "square.split.diagonal.fill",
        "square.grid.2x2", "square.grid.2x2.fill",
        "square.grid.3x3", "square.grid.3x3.fill",

        // MARK: - Math & Science (30+)
        "plus.forwardslash.minus",
        "minus.forwardslash.plus",
        "multiply", "divide",
        "equal", "lessthan", "greaterthan",
        "sum", "percent",
        "infinity",
        "function",
        "x.squareroot",
        "x.squareroot.circle", "x.squareroot.circle.fill",
        "x.squareroot.square", "x.squareroot.square.fill",
        "xmark.bin", "xmark.bin.fill",
        "xmark.bin.circle", "xmark.bin.circle.fill",
        "checkmark.gobackward",
        "checkmark.circle.badge.questionmark", "checkmark.circle.badge.questionmark.fill",
        "checkmark.circle.badge.xmark", "checkmark.circle.badge.xmark.fill",
        "checkmark.diamond", "checkmark.diamond.fill",
        "checkmark.rectangle", "checkmark.rectangle.fill",
        "checkmark.rectangle.portrait", "checkmark.rectangle.portrait.fill",
        "checkmark.seal", "checkmark.seal.fill",
        "checkmark.shield", "checkmark.shield.fill",
        "checkmark.message", "checkmark.message.fill",
        "checkmark.bubble", "checkmark.bubble.fill",
        "checkmark.bubble.circle", "checkmark.bubble.circle.fill",
        "xmark.seal", "xmark.seal.fill",
        "exclamationmark.seal", "exclamationmark.seal.fill",
        "questionmark.folder", "questionmark.folder.fill",
        "questionmark.folder.circle", "questionmark.folder.circle.fill",
        "questionmark.square.dashed",
        "questionmark.braces.square",
        "exclamationmark.2", "exclamationmark.3",
        "exclamationmark.octagon", "exclamationmark.octagon.fill",

        // MARK: - Media & Playback (60+)
        "play", "play.fill",
        "play.circle", "play.circle.fill",
        "play.square", "play.square.fill",
        "play.rectangle", "play.rectangle.fill",
        "play.slash", "play.slash.fill",
        "pause", "pause.fill",
        "pause.circle", "pause.circle.fill",
        "pause.rectangle", "pause.rectangle.fill",
        "stop", "stop.fill",
        "stop.circle", "stop.circle.fill",
        "forward", "forward.fill",
        "forward.circle", "forward.circle.fill",
        "backward", "backward.fill",
        "backward.circle", "backward.circle.fill",
        "backward.end", "backward.end.fill",
        "backward.end.alt", "backward.end.alt.fill",
        "forward.end", "forward.end.fill",
        "forward.end.alt", "forward.end.alt.fill",
        "shuffle", "shuffle.circle", "shuffle.circle.fill",
        "repeat", "repeat.circle", "repeat.circle.fill",
        "repeat.1", "repeat.1.circle", "repeat.1.circle.fill",
        "infinity", "infinity.circle", "infinity.circle.fill",
        "speaker", "speaker.fill",
        "speaker.circle", "speaker.circle.fill",
        "speaker.slash", "speaker.slash.fill",
        "speaker.slash.circle", "speaker.slash.circle.fill",
        "speaker.zzz", "speaker.zzz.fill",
        "speaker.wave.1", "speaker.wave.1.fill",
        "speaker.wave.2", "speaker.wave.2.fill",
        "speaker.wave.2.circle", "speaker.wave.2.circle.fill",
        "speaker.wave.3", "speaker.wave.3.fill",
        "speaker.wave.3.circle", "speaker.wave.3.circle.fill",
        "speaker.badge.exclamationmark", "speaker.badge.exclamationmark.fill",
        "hifispeaker", "hifispeaker.fill",
        "hifispeaker.2", "hifispeaker.2.fill",
        "hifispeaker.and.appletv", "hifispeaker.and.appletv.fill",
        "hifispeaker.2.and.appletv", "hifispeaker.2.and.appletv.fill",
        "minus.plus.batteryblock", "minus.plus.batteryblock.fill",
        "headphones", "headphones.circle", "headphones.circle.fill",
        "headphones.fill",
        "earbuds", "earbuds.case", "earbuds.case.fill",
        "earbuds.2", "earbuds.2.case", "earbuds.2.case.fill",
        "ear.and.waveform",
        "ear.badge.checkmark", "ear.trianglebadge.exclamationmark",
        "ear.fill", "ear.badge.checkmark.fill", "ear.trianglebadge.exclamationmark.fill",
        "hearingdevice.ear",
        "waveform", "waveform.circle", "waveform.circle.fill",
        "waveform.slash",
        "waveform.badge.plus", "waveform.badge.minus",
        "waveform.badge.exclamationmark",
        "waveform.and.mic",
        "waveform.and.magnifyingglass",
        "waveform.path.ecg",
        "waveform.path.ecg.rectangle", "waveform.path.ecg.rectangle.fill",
        "waveform.path.badge.plus",
        "waveform.path.badge.minus",
        "waveform.path", "waveform.path.fill",
        "movieclapper", "movieclapper.fill",
        "film", "film.fill",
        "film.circle", "film.circle.fill",
        "film.stack", "film.stack.fill",
        "play.tv", "play.tv.fill",
        "play.display", "play.display.fill",
        "tv.inset.filled",
        "tv.and.hifispeaker.fill",
        "tv.and.mediabox",
        "music.note",
        "music.note.list",
        "music.quarternote.3",
        "music.mic",
        "music.mic.circle", "music.mic.circle.fill",

        // MARK: - Objects & Items (60+)
        "suit.heart", "suit.heart.fill",
        "suit.club", "suit.club.fill",
        "suit.diamond", "suit.diamond.fill",
        "suit.spade", "suit.spade.fill",
        "star", "star.fill",
        "star.leadinghalf.fill",
        "star.trailinghalf.fill",
        "star.circle", "star.circle.fill",
        "star.square", "star.square.fill",
        "flag", "flag.fill",
        "flag.circle", "flag.circle.fill",
        "flag.square", "flag.square.fill",
        "flag.slash", "flag.slash.fill",
        "flag.slash.circle", "flag.slash.circle.fill",
        "flag.badge.ellipsis", "flag.fill.badge.ellipsis",
        "flag.2.crossed", "flag.2.crossed.fill",
        "flag.2.crossed.circle", "flag.2.crossed.circle.fill",
        "flag.checkered",
        "flag.checkered.circle", "flag.checkered.circle.fill",
        "flag.filled.and.flag.crossed",
        "flag.checkered.2.crossed",
        "location", "location.fill",
        "location.circle", "location.circle.fill",
        "location.square", "location.square.fill",
        "location.slash", "location.slash.fill",
        "location.slash.circle", "location.slash.circle.fill",
        "mappin", "mappin.fill",
        "mappin.circle", "mappin.circle.fill",
        "mappin.slash", "mappin.slash.fill",
        "mappin.and.ellipse",
        "map", "map.fill",
        "map.circle", "map.circle.fill",
        "at", "at.circle", "at.circle.fill",
        "at.badge.plus", "at.badge.minus",
        "qrcode",
        "barcode",
        "viewfinder",
        "viewfinder.circle", "viewfinder.circle.fill",
        "barcode.viewfinder",
        "qrcode.viewfinder",
        "plus.viewfinder",
        "camera.viewfinder",
        "doc.viewfinder", "doc.viewfinder.fill",
        "location.viewfinder",
        "location.fill.viewfinder",
        "person.fill.viewfinder",
        "person.crop.square.fill",
        "person.crop.circle.fill.badge.checkmark",
        "person.crop.circle.fill.badge.xmark",
        "person.crop.circle.badge.questionmark.fill",
        "person.crop.circle.badge.exclamationmark.fill",
        "key", "key.fill",
        "key.horizontal", "key.horizontal.fill",
        "key.radiowaves.forward", "key.radiowaves.forward.fill",
        "key.radiowaves.forward.slash", "key.radiowaves.forward.slash.fill",
        "lock", "lock.fill",
        "lock.circle", "lock.circle.fill",
        "lock.square", "lock.square.fill",
        "lock.square.stack", "lock.square.stack.fill",
        "lock.rectangle", "lock.rectangle.fill",
        "lock.rectangle.stack", "lock.rectangle.stack.fill",
        "lock.shield", "lock.shield.fill",
        "lock.slash", "lock.slash.fill",
        "lock.slash.circle", "lock.slash.circle.fill",
        "lock.open", "lock.open.fill",
        "lock.open.trianglebadge.exclamationmark", "lock.open.trianglebadge.exclamationmark.fill",
        "lock.rotation", "lock.rotation.open",
        "hourglass", "hourglass.circle", "hourglass.circle.fill",
        "hourglass.badge.plus",
        "hourglass.bottomhalf.filled",
        "hourglass.tophalf.filled",
        "dice", "dice.fill",
        "die.face.1", "die.face.1.fill",
        "die.face.2", "die.face.2.fill",
        "die.face.3", "die.face.3.fill",
        "die.face.4", "die.face.4.fill",
        "die.face.5", "die.face.5.fill",
        "die.face.6", "die.face.6.fill",
        "pianokeys", "pianokeys.inverse",
        "tuningfork",
        "paintbrush", "paintbrush.fill",
        "paintbrush.pointed", "paintbrush.pointed.fill",
        "level", "level.fill",
        "wrench.adjustable", "wrench.adjustable.fill",
        "hammer", "hammer.fill",
        "hammer.circle", "hammer.circle.fill",
        "screwdriver", "screwdriver.fill",
        "screw", "screw.fill",
        "magnifyingglass",
        "magnifyingglass.circle", "magnifyingglass.circle.fill",
        "magnifyingglass.badge.plus", "magnifyingglass.badge.minus",
        "magnifyingglass.badge.ellipsis",
        "magnifyingglass.2",
        "binoculars", "binoculars.fill",
        "circle.bottomthird.split",
        "circle.lefthalf.filled.righthalf.striped.horizontal",
        "circle.lefthalf.striped.horizontal.righthalf.filled",
        "diamond.lefthalf.filled.righthalf.striped.horizontal",
        "diamond.lefthalf.striped.horizontal.righthalf.filled",

        // MARK: - Gaming & Fun (20+)
        "gamecontroller", "gamecontroller.fill",
        "l.joystick", "l.joystick.fill",
        "l.joystick.tilt.left", "l.joystick.tilt.left.fill",
        "l.joystick.tilt.right", "l.joystick.tilt.right.fill",
        "l.joystick.tilt.up", "l.joystick.tilt.up.fill",
        "l.joystick.tilt.down", "l.joystick.tilt.down.fill",
        "l.joystick.press.down", "l.joystick.press.down.fill",
        "r.joystick", "r.joystick.fill",
        "r.joystick.tilt.left", "r.joystick.tilt.left.fill",
        "r.joystick.tilt.right", "r.joystick.tilt.right.fill",
        "r.joystick.tilt.up", "r.joystick.tilt.up.fill",
        "r.joystick.tilt.down", "r.joystick.tilt.down.fill",
        "r.joystick.press.down", "r.joystick.press.down.fill",
        "circle.grid.cross", "circle.grid.cross.fill",
        "circle.grid.cross.left.filled",
        "circle.grid.cross.up.filled",
        "circle.grid.cross.right.filled",
        "circle.grid.cross.down.filled",
        "dpad", "dpad.fill",
        "dpad.left.filled", "dpad.up.filled", "dpad.right.filled", "dpad.down.filled",
        "circle.circle", "circle.circle.fill",
        "square.circle", "square.circle.fill",
        "triangle.circle", "triangle.circle.fill",
        "a.circle", "a.circle.fill",
        "b.circle", "b.circle.fill",
        "x.circle", "x.circle.fill",
        "y.circle", "y.circle.fill",
        "rectangle.compress.vertical",
        "rectangle.expand.vertical",
        "rectangle.split.1x2", "rectangle.split.1x2.fill",
        "rectangle.split.2x1", "rectangle.split.2x1.fill",
        "rectangle.split.2x2", "rectangle.split.2x2.fill",
        "tablecells", "tablecells.fill",
        "tablecells.badge.ellipsis", "tablecells.fill.badge.ellipsis",
        "rectangle.split.3x1", "rectangle.split.3x1.fill",
        "rectangle.split.3x3", "rectangle.split.3x3.fill",
        "lanyardcard", "lanyardcard.fill",
        "lanyardcard.and.touchid",

        // MARK: - SF Symbols 5+ (New - 50+)
        "accessibility", "accessibility.fill",
        "figure.child", "figure.child.circle", "figure.child.circle.fill",
        "figure.child.and.lock", "figure.child.and.lock.fill",
        "figure.child.and.lock.open", "figure.child.and.lock.open.fill",
        "figure.walk.arrival", "figure.walk.arrival.fill",
        "figure.walk.departure", "figure.walk.departure.fill",
        "figure.run.treadmill", "figure.run.treadmill.fill",
        "figure.run.track.and.field", "figure.run.track.and.field.fill",
        "figure.american.football",
        "figure.archery",
        "figure.australian.football",
        "figure.badminton",
        "figure.barre",
        "figure.baseball",
        "figure.basketball",
        "figure.bowling",
        "figure.boxing",
        "figure.climbing",
        "figure.cooldown",
        "figure.core.training",
        "figure.cricket",
        "figure.skiing.crosscountry",
        "figure.curling",
        "figure.dance",
        "figure.disc.sports",
        "figure.skiing.downhill",
        "figure.elliptical",
        "figure.equestrian.sports",
        "figure.fencing",
        "figure.fishing",
        "figure.flexibility",
        "figure.strengthtraining.functional",
        "figure.golf",
        "figure.gymnastics",
        "figure.hand.cycling",
        "figure.hiking",
        "figure.hockey",
        "figure.hunting",
        "figure.indoor.cycle",
        "figure.jumprope",
        "figure.kickboxing",
        "figure.lacrosse",
        "figure.martial.arts",
        "figure.mind.and.body",
        "figure.mixed.cardio",
        "figure.open.water.swim",
        "figure.outdoor.cycle",
        "figure.ocean.sports",
        "figure.pickleball",
        "figure.pilates",
        "figure.play",
        "figure.pool.swim",
        "figure.racquetball",
        "figure.rolling",
        "figure.rower",
        "figure.rugby",
        "figure.sailing",
        "figure.skating",
        "figure.skiing",
        "figure.snowboarding",
        "figure.soccer",
        "figure.socialdance",
        "figure.softball",
        "figure.squash",
        "figure.stair.stepper",
        "figure.stairs",
        "figure.step.training",
        "figure.surfing",
        "figure.table.tennis",
        "figure.taichi",
        "figure.tennis",
        "figure.track.and.field",
        "figure.strengthtraining.traditional",
        "figure.volleyball",
        "figure.water.fitness",
        "figure.waterpolo",
        "figure.wrestling",
        "figure.yoga",
        "aqi.low", "aqi.medium", "aqi.high",
        "car.top.radiowaves.rear.left", "car.top.radiowaves.rear.right",
        "car.top.radiowaves.rear",
        "car.top.radiowaves.front", "car.top.radiowaves.front.and.rear",
        "car.top.lane.arrow.left",
        "car.top.lane.arrow.right",
        "car.top.lane.arrow.triangle.merge",
        "car.top.lane.arrow.triangle.split",
        "car.top.lane.arrow.curved.left",
        "car.top.lane.arrow.curved.right",
        "car.top.lane.dashed.arrow.left",
        "car.top.lane.dashed.arrow.right",
        "car.top.lane.dashed.badge.steeringwheel",
        "car.top.lane.dashed.badge.steeringwheel.fill",
        "car.rear.temporary"
    ])).sorted()

    // MARK: - Categorized Icons (filtered by availability)

    func iconsByCategory() -> [String: [String]] {
        let allCategories = getAllCategories()

        // Filter each category to only include available icons
        var filtered: [String: [String]] = [:]
        for (category, icons) in allCategories {
            let available = icons.filter { icon in
                #if os(macOS)
                NSImage(systemSymbolName: icon, accessibilityDescription: nil) != nil
                #else
                UIImage(systemName: icon) != nil
                #endif
            }
            if !available.isEmpty {
                filtered[category] = available
            }
        }
        return filtered
    }

    /// Returns all categories without filtering - used for async loading
    func getAllCategories() -> [String: [String]] {
        return [
            // MARK: Arrows & Navigation
            "Arrows": [
                "arrow.left", "arrow.right", "arrow.up", "arrow.down",
                "arrow.left.circle", "arrow.right.circle", "arrow.up.circle", "arrow.down.circle",
                "arrow.left.circle.fill", "arrow.right.circle.fill", "arrow.up.circle.fill", "arrow.down.circle.fill",
                "arrow.clockwise", "arrow.counterclockwise",
                "arrow.uturn.left", "arrow.uturn.right",
                "arrow.triangle.2.circlepath",
                "chevron.left", "chevron.right", "chevron.up", "chevron.down",
                "forward", "backward",
                "goforward", "gobackward"
            ],

            // MARK: Media & Playback
            "Media": [
                "play", "play.fill", "play.circle", "play.circle.fill",
                "pause", "pause.fill", "pause.circle", "pause.circle.fill",
                "stop", "stop.fill", "stop.circle", "stop.circle.fill",
                "shuffle", "shuffle.circle", "shuffle.circle.fill",
                "repeat", "repeat.circle", "repeat.circle.fill",
                "speaker", "speaker.fill", "speaker.slash", "speaker.slash.fill",
                "headphones", "headphones.circle", "headphones.circle.fill",
                "music.note", "music.note.list",
                "waveform", "waveform.circle", "waveform.circle.fill"
            ],

            // MARK: Communication
            "Communication": [
                "envelope", "envelope.fill", "envelope.circle", "envelope.circle.fill",
                "paperplane", "paperplane.fill", "paperplane.circle", "paperplane.circle.fill",
                "tray", "tray.fill", "tray.full", "tray.full.fill",
                "bubble.left", "bubble.left.fill",
                "bubble.right", "bubble.right.fill",
                "phone", "phone.fill", "phone.circle", "phone.circle.fill",
                "video", "video.fill", "video.circle", "video.circle.fill",
                "mic", "mic.fill", "mic.circle", "mic.circle.fill",
                "camera", "camera.fill", "camera.circle", "camera.circle.fill"
            ],

            // MARK: Organization
            "Organization": [
                "folder", "folder.fill", "folder.circle", "folder.circle.fill",
                "folder.badge.plus", "folder.fill.badge.plus",
                "bookmark", "bookmark.fill", "bookmark.circle", "bookmark.circle.fill",
                "tag", "tag.fill", "tag.circle", "tag.circle.fill",
                "archivebox", "archivebox.fill",
                "tray", "tray.fill",
                "doc", "doc.fill", "doc.circle", "doc.circle.fill",
                "doc.text", "doc.text.fill",
                "list.bullet", "list.dash", "list.number",
                "checklist", "checklist.checked"
            ],

            // MARK: Technology
            "Technology": [
                "iphone", "iphone.fill",
                "ipad", "ipad.fill",
                "laptopcomputer", "laptopcomputer.and.arrow.down",
                "desktopcomputer",
                "wifi", "wifi.circle", "wifi.circle.fill",
                "icloud", "icloud.fill", "icloud.circle", "icloud.circle.fill",
                "network",
                "antenna.radiowaves.left.and.right",
                "cpu", "memorychip",
                "keyboard", "keyboard.fill",
                "printer", "printer.fill"
            ],

            // MARK: Social
            "Social": [
                "person", "person.fill", "person.circle", "person.circle.fill",
                "person.2", "person.2.fill",
                "person.3", "person.3.fill",
                "heart", "heart.fill", "heart.circle", "heart.circle.fill",
                "star", "star.fill", "star.circle", "star.circle.fill",
                "hand.thumbsup", "hand.thumbsup.fill",
                "hand.thumbsdown", "hand.thumbsdown.fill",
                "hand.wave", "hand.wave.fill",
                "hand.raised", "hand.raised.fill"
            ],

            // MARK: Objects
            "Objects": [
                "house", "house.fill", "house.circle", "house.circle.fill",
                "gearshape", "gearshape.fill", "gearshape.circle", "gearshape.circle.fill",
                "lock", "lock.fill", "lock.circle", "lock.circle.fill",
                "lock.open", "lock.open.fill",
                "key", "key.fill",
                "bell", "bell.fill", "bell.circle", "bell.circle.fill",
                "magnifyingglass",
                "flag", "flag.fill", "flag.circle", "flag.circle.fill",
                "mappin", "mappin.fill", "mappin.circle", "mappin.circle.fill",
                "map", "map.fill",
                "location", "location.fill", "location.circle", "location.circle.fill"
            ],

            // MARK: Finance
            "Finance": [
                "creditcard", "creditcard.fill", "creditcard.circle", "creditcard.circle.fill",
                "banknote", "banknote.fill",
                "dollarsign.circle", "dollarsign.circle.fill",
                "eurosign.circle", "eurosign.circle.fill",
                "yensign.circle", "yensign.circle.fill",
                "cart", "cart.fill",
                "bag", "bag.fill",
                "giftcard", "giftcard.fill",
                "wallet.bifold", "wallet.bifold.fill"
            ],

            // MARK: Weather
            "Weather": [
                "sun.min", "sun.min.fill",
                "sun.max", "sun.max.fill",
                "cloud", "cloud.fill",
                "cloud.sun", "cloud.sun.fill",
                "cloud.moon", "cloud.moon.fill",
                "cloud.rain", "cloud.rain.fill",
                "cloud.snow", "cloud.snow.fill",
                "cloud.bolt", "cloud.bolt.fill",
                "moon", "moon.fill", "moon.circle", "moon.circle.fill",
                "snowflake",
                "wind",
                "tornado",
                "bolt", "bolt.fill"
            ],

            // MARK: Transportation
            "Transportation": [
                "car", "car.fill", "car.circle", "car.circle.fill",
                "bus", "bus.fill",
                "tram", "tram.fill",
                "airplane", "airplane.fill", "airplane.circle", "airplane.circle.fill",
                "bicycle", "bicycle.circle", "bicycle.circle.fill",
                "fuel.pump", "fuel.pump.fill"
            ],

            // MARK: Editing & Creation
            "Editing": [
                "pencil", "pencil.circle", "pencil.circle.fill",
                "square.and.pencil",
                "scribble",
                "lasso",
                "crop",
                "wand.and.rays", "wand.and.rays.inverse",
                "paintbrush", "paintbrush.fill",
                "paintpalette", "paintpalette.fill",
                "textformat", "textformat.alt"
            ],

            // MARK: Symbols
            "Symbols": [
                "checkmark", "checkmark.circle", "checkmark.circle.fill",
                "xmark", "xmark.circle", "xmark.circle.fill",
                "plus", "plus.circle", "plus.circle.fill",
                "minus", "minus.circle", "minus.circle.fill",
                "questionmark", "questionmark.circle", "questionmark.circle.fill",
                "exclamationmark", "exclamationmark.circle", "exclamationmark.circle.fill",
                "info", "info.circle", "info.circle.fill",
                "circle", "circle.fill",
                "square", "square.fill",
                "triangle", "triangle.fill",
                "diamond", "diamond.fill",
                "star", "star.fill",
                "heart", "heart.fill"
            ],

            // MARK: Gaming
            "Gaming": [
                "gamecontroller", "gamecontroller.fill",
                "dice", "dice.fill",
                "die.face.1", "die.face.2", "die.face.3",
                "die.face.4", "die.face.5", "die.face.6",
                "l.joystick", "l.joystick.fill",
                "r.joystick", "r.joystick.fill",
                "dpad", "dpad.fill"
            ],

            // MARK: Health & Fitness
            "Health": [
                "heart", "heart.fill",
                "bolt.heart", "bolt.heart.fill",
                "lungs", "lungs.fill",
                "stethoscope", "stethoscope.circle", "stethoscope.circle.fill",
                "bandage", "bandage.fill",
                "cross", "cross.fill",
                "pills", "pills.fill",
                "brain", "brain.fill"
            ],

            // MARK: Food & Drink
            "Food": [
                "leaf", "leaf.fill",
                "carrot", "carrot.fill",
                "fork.knife",
                "cup.and.saucer", "cup.and.saucer.fill",
                "mug", "mug.fill",
                "wineglass", "wineglass.fill",
                "birthday.cake", "birthday.cake.fill",
                "popcorn", "popcorn.fill"
            ],

            // MARK: Animals
            "Animals": [
                "pawprint", "pawprint.fill",
                "bird", "bird.fill",
                "fish", "fish.fill",
                "tortoise", "tortoise.fill",
                "hare", "hare.fill",
                "ant", "ant.fill",
                "ladybug", "ladybug.fill"
            ],

            // MARK: Sports
            "Sports": [
                "figure.walk", "figure.run", "figure.hike",
                "figure.swim",
                "figure.cycle",
                "figure.skiing", "figure.snowboarding",
                "figure.soccer", "figure.basketball",
                "figure.baseball", "figure.tennis",
                "figure.golf",
                "figure.yoga",
                "trophy", "trophy.fill",
                "medal", "medal.fill"
            ],

            // MARK: Development
            "Development": [
                "chevron.left.forwardslash.chevron.right",
                "terminal", "terminal.fill",
                "curlybraces", "curlybraces.square", "curlybraces.square.fill",
                "number", "number.circle", "number.circle.fill",
                "function", "function.circle", "function.circle.fill",
                "command", "command.circle", "command.circle.fill",
                "option", "option.circle", "option.circle.fill",
                "control", "control.circle", "control.circle.fill"
            ],

            // MARK: Time
            "Time": [
                "clock", "clock.fill", "clock.circle", "clock.circle.fill",
                "timer",
                "stopwatch", "stopwatch.fill",
                "alarm", "alarm.fill",
                "hourglass", "hourglass.circle", "hourglass.circle.fill",
                "calendar", "calendar.circle", "calendar.circle.fill"
            ]
        ]
    }

    // MARK: - Helper Methods

    func randomIcon() -> String {
        availableIcons.randomElement() ?? "folder.fill"
    }

    func isValidSymbol(_ name: String) -> Bool {
        availableIcons.contains(name)
    }

    func searchIcons(query: String) -> [String] {
        let lowerQuery = query.lowercased()
        return availableIcons.filter { icon in
            icon.lowercased().contains(lowerQuery)
        }
    }
}
